// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIp9RWzxA0VZsYByudrVSZUSOrs7kng0k',
    appId: '1:1016201519964:web:bfc2c46862fcb0b9319799',
    messagingSenderId: '1016201519964',
    projectId: 'horizon-task-11766',
    authDomain: 'horizon-task-11766.firebaseapp.com',
    storageBucket: 'horizon-task-11766.firebasestorage.app',
    measurementId: 'G-4QM5J86X1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbUYGkN250UxA7xpW0gDS-dqtT36F27H4',
    appId: '1:1016201519964:android:8dedb707a90223a3319799',
    messagingSenderId: '1016201519964',
    projectId: 'horizon-task-11766',
    storageBucket: 'horizon-task-11766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK8D-coL2qOa1aGB4HVnGp6VL626INrWs',
    appId: '1:1016201519964:ios:ef59b098c069da7b319799',
    messagingSenderId: '1016201519964',
    projectId: 'horizon-task-11766',
    storageBucket: 'horizon-task-11766.firebasestorage.app',
    iosBundleId: 'com.example.horizonMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK8D-coL2qOa1aGB4HVnGp6VL626INrWs',
    appId: '1:1016201519964:ios:ef59b098c069da7b319799',
    messagingSenderId: '1016201519964',
    projectId: 'horizon-task-11766',
    storageBucket: 'horizon-task-11766.firebasestorage.app',
    iosBundleId: 'com.example.horizonMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIp9RWzxA0VZsYByudrVSZUSOrs7kng0k',
    appId: '1:1016201519964:web:d769ffc0da050fbb319799',
    messagingSenderId: '1016201519964',
    projectId: 'horizon-task-11766',
    authDomain: 'horizon-task-11766.firebaseapp.com',
    storageBucket: 'horizon-task-11766.firebasestorage.app',
    measurementId: 'G-03GN7SGFH1',
  );
}
